version: "3.9"
services:
  redis-zero:
    container_name: redis-zero
    hostname: redis-zero
    image: redis
    ports:
    - "6380:6379"

  redis:
    container_name: redis
    image: "redis:6.2-alpine"
    restart: "always"
    ports:
    - "6381:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes --requirepass redispass
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  redis-commander-multi:
    container_name: redis-commander-multi
    hostname: redis-commander-multi
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:192.168.56.74:6380,WithPass:192.168.56.74:6381:0:redispass
    ports:
    - "8081:8081"

  redis-commanders:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
    - REDIS_HOST=192.168.56.74
    - REDIS_PORT=6381
    - REDIS_USERNAME=ivan
    - REDIS_PASSWORD=pass
    - PORT=8082
    ports:
    - "8082:8082"
    profiles:
      - donotstart

volumes:
  redis:
