[local]
127.0.0.1

[local:vars]
ansible_connection=local

[slave]
10.224.128.102
10.224.128.101

[slave:vars]
ansible_connection=ssh

[sentinels]
10.224.128.111
10.224.128.102
10.224.128.101

[sentinels:vars]
ansible_python_interpreter=python3
ansible_connection=ssh
ansible_ssh_port=22
ansible_become=yes
ansible_user=root
ansible_ssh_pass=***
ansible_become_pass=***
